### ISSUE TITLE
[Question] Can I send to frame without loading in index

### ISSUE THREAD

**Issue by oleteacher** [dbudde/frameLoader#1]
Hi. I am a school teacher and stumbled across your frameLoader while researching my question.

I am not sure if your frameLoader will work for me, so I please ask:

Can I send message to frame.html without loading it in the index.html?

Need to send simple message to a blog network we have setup in classroom and on low budget:)

May sound like a crazy question and for my skill level may very well be crazy...

Thanks for your time.

**Comment by dbudde** [comment]
Hello.  To start off, I'm not sure I completely understand your question.  You can feel free to contact me through my profile so that we can take this conversation over e-mail instead.

If you are wanting to send messages across windows, then I believe you actually want to work with my [windowMessenger](https://github.com/dbudde/windowMessenger) project.  **frameLoader** actually runs on top of **windowMessenger** in order to communicate between windows.

**Comment by oleteacher** [comment]
I am fairly new to GitHub and it was just explained to me that this is not the place to ask question. So, my bad. Lesson learned.

Will take a look at your windowMessenger and see if can figure it out. Basically just need to send message to iframed page telling students internet will be shut down in X number of minutes.

Thanks again for your time.
